import {createMockRecords} from './mock-adapter.js';
const STATUS_LABELS={pending:'Pending',processing:'Processing',completed:'Completed',duplicate:'Duplicate',failed:'Failed',review_required:'Review required'};
const fileInput=document.querySelector('#file-input'), fileList=document.querySelector('#file-list'), dropzone=document.querySelector('#dropzone'), progressWrap=document.querySelector('#progress-wrap'), progressBar=document.querySelector('#progress-bar'), progressText=document.querySelector('#progress-text'), progressValue=document.querySelector('#progress-value'), batchState=document.querySelector('#batch-state'), errorBox=document.querySelector('#file-error');
function sizeLabel(bytes){return `${Math.max(1,Math.round(bytes/1024))} KB`}
function render(records){fileList.innerHTML=records.map(record=>`<tr><td>${escapeHtml(record.name)}<span class="file-meta">${sizeLabel(record.size)} · ${escapeHtml(record.type||'image')}</span></td><td><span class="file-meta">${escapeHtml(record.hash)}</span></td><td>${escapeHtml(record.preservation)}</td><td><span class="status ${record.status}">${STATUS_LABELS[record.status]}</span></td></tr>`).join('');}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function showError(message){document.querySelector('#error-message').textContent=message;errorBox.hidden=false;errorBox.focus();batchState.textContent='Needs attention';batchState.style.color='var(--red)';}
function process(files){if(!files.length)return; if(files.length>50){showError('Choose 50 files or fewer per batch.');return;} errorBox.hidden=true;const records=createMockRecords(files);render(records);progressWrap.hidden=false;batchState.textContent='Processing';batchState.style.color='var(--purple)';let progress=0;const timer=setInterval(()=>{progress=Math.min(100,progress+25);progressBar.style.width=`${progress}%`;progressValue.textContent=`${progress}%`;progressText.textContent=progress===100?'Batch ready':'Preparing files…';if(progress===100){clearInterval(timer);records.forEach((r,i)=>{if(r.status==='pending')r.status='completed';});render(records);batchState.textContent='Complete';batchState.style.color='var(--green)';}},180);}
fileInput.addEventListener('change',event=>process(event.target.files));['dragenter','dragover'].forEach(name=>dropzone.addEventListener(name,event=>{event.preventDefault();dropzone.classList.add('active');}));['dragleave','drop'].forEach(name=>dropzone.addEventListener(name,event=>{event.preventDefault();dropzone.classList.remove('active');}));dropzone.addEventListener('drop',event=>process(event.dataTransfer.files));
